# Generated CI/CD Pipeline YAML
# This YAML is compatible with GitHub Actions

# Pipeline: tutorial_pipeline
name: tutorial_pipeline

on:
  workflow_dispatch:

jobs:
  build_test:
    # Build and test the application
    runs-on: ubuntu-latest
    steps:
            - name: command_88882
              uses: actions/checkout@v4
            - name: install dependencies
              uses: actions/setup-python@v4
              with:
                        python-version: '3.9'
            - name: pip
              run: pip install -r requirements.txt
            - name: test
              run: pytest
